### PR TITLE
Some changes to typo and intrinsics

### PR DESCRIPTION
**Pull request by Geng-Qi**
I have previously suggested some issues about intrinsic.
Many of these have been fixed, but there are still some missing.
So this commit contains those omissions and some of my new findings and understandings.
I hope this approach will make it easier for you to make some fix.

### CODE REVIEW

**Comment by Geng-Qi** [comment]
> Hi Geng-Qi,
> I wonder how your implement RVP in gcc. I think adding `const` qualifier is useless for builtin approach, like [andes-gcc](https://github.com/andestech/gcc/blob/73223a19c33ea9fbd74a79d5142c8a002d70075d/gcc/config/riscv/riscv-builtins.c).

Thank you for your reply.

My cases：

without ‘const’
`
#include <stdint.h>
typedef short int16x4_t __attribute__ ((vector_size (8)));
__extension__ static __inline __attribute__ ((__always_inline__, artificial, flatten, gnu_inline))
int16x4_t __rv__v_sclip16(int16x4_t a, uint32_t b) {
  return __builtin_riscv_sclip16_v4hi(a, b);
}

int16x4_t
foo(int16x4_t a)
{
  return __rv__v_sclip16(a,3);
}
`

with ‘const’
`
#include <stdint.h>
typedef short int16x4_t __attribute__ ((vector_size (8)));
__extension__ static __inline __attribute__ ((__always_inline__, artificial, flatten, gnu_inline))
int16x4_t __rv__v_sclip16(int16x4_t a, const uint32_t b) {
  return __builtin_riscv_sclip16_v4hi(a, b);
}

int16x4_t
foo(int16x4_t a)
{
  return __rv__v_sclip16(a,3);
}
`

I complied these two under -O0 and dumped files，the differences occured in pass 'early inline'.

Differences in .einline:

without ‘const’
`
...
  <bb 2> :
  a_5 = a_2(D);
  b_6 = 3;
  _7 = __builtin_riscv_sclip16_v4hi (a_5, b_6);
...
`

with 'const'
`
...
  <bb 2> :
  a_5 = a_2(D);
  _6 = __builtin_riscv_sclip16_v4hi (a_5, 3);
...
`

The key code is about here:

gcc/tree-inline.c:
`
....
  /* If there is no setup required and we are in SSA, take the easy route
     replacing all SSA names representing the function parameter by the
     SSA name passed to function.

     We need to construct map for the variable anyway as it might be used
     in different SSA names when parameter is set in function.

     Do replacement at -O0 for const arguments replaced by constant.
     This is important for builtin_constant_p and other construct requiring
     constant argument to be visible in inlined function body.  */
  if (gimple_in_ssa_p (cfun) && rhs && def && is_gimple_reg (p)
      && (optimize
          || (TREE_READONLY (p)
	      && is_gimple_min_invariant (rhs)))
      && (TREE_CODE (rhs) == SSA_NAME
	  || is_gimple_min_invariant (rhs))
      && !SSA_NAME_OCCURS_IN_ABNORMAL_PHI (def))
    {
      insert_decl_map (id, def, rhs);
      return insert_init_debug_bind (id, bb, var, rhs, NULL);
    }
...
`

Due to the difference above, I cannot generate the ‘sclip’ without ‘const’.

**Review by chuanhua — APPROVED** [review]
These fixes are correct.

**Review by chuanhua — APPROVED** [review]

**Review by chuanhua — APPROVED** [review]

**Review by chuanhua — APPROVED** [review]

**Review by chuanhua — APPROVED** [review]

**Review by chuanhua — APPROVED** [review]

**Comment by fakepaper56** [comment]
I still think we should not modify the spec for 2 reason,
1. Constant argument is for implementation but not for user's view. Adding `const` looks not concise.
2. You could add `const` in your header without any modification in spec.

**Review by chuanhua — CHANGES_REQUESTED** [review]
Could you remove this commit? It seems that there are other ways to add the "const" keyword before using the intrinsic function.

**Comment by Geng-Qi** [comment]
> Could you remove this commit? It seems that there are other ways to add the "const" keyword before using the intrinsic function.

I have dropped it.

**Comment by linsinan1995** [comment]
sry for commenting on a merged pr.

```c
- intXLEN_t __rv__v_khmtt(int16x4_t a, int16x4_t b);
+ intXLEN_t __rv__v_khmtt(int16x2_t a, int16x2_t b);
```
why we don't change the return type to int32_t, just like how kdm* works?

**Comment by chuanhua** [comment]
I have taken your suggestion in 3d36d5c.

**Pull request merged**
